const images = {
  play: require('./play-button.png'),
  background:require('./backgroundDrawer.png'),
  logo:require('./Vector.png'),
  playBtn:require('./play1.png'),
  pausebtn: require("./pause1.png"),
  splash2Img: require('./splash2Img.png'),
  homeIcon:require('./HomeIcon.png'),
  forYouIcon:require('./forYouIcon.png'),
  audioIcon:require('./AudioIcon.png'),
  homeBack:require('./HomeBackGround.png'),
  English: require("./English.png"),
  Urdu: require('./Urdu.png'),
  Punjabi:require('./Punjabi.png'),
  Image:require('./Image.png'),
  Profile:require('./Profile.png'),
  Sticker:require('./Sticker.png'),
  whatsapp:require('./whatsapp.png'),
  downarrow:require('./downarrow.png'),
  back:require('./back.png'),
  catcover:require('./catcover.png'),
  download:require('./download.png'),
  Group:require('./Group.png'),
  share:require('./share.png'),
  cross:require('./cross.png'),
  verticalDots:require('./moreDots.png'),
  cancel:require('./cancel.png'),
  shareBlack:require('./shareBlack.png'),
  downloadBlack:require('./downloadBlack.png'),
  downArrow:require('./down-arrow.png'),
  verticalDotsWhite:require('./verticalDotsWhite.png')
};

export default images;